# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_cover', models.CharField(choices=[('miękka', 'miękka'), ('twarda', 'twarda')], default='miękka', max_length=6)),
                ('publisher', models.CharField(max_length=50)),
                ('premier_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('publish_date', models.DateField(blank=True)),
                ('page_number', models.IntegerField(default=1)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100)),
                ('image', models.ImageField(default='book.jpg', upload_to='media')),
                ('delete', models.BooleanField(blank=True, default=None)),
            ],
        ),
    ]
