# Generated by Django 3.1.7 on 2021-03-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='premier_date',
            new_name='data_premiery',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='data_publikacji',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page_number',
            new_name='liczba_stron',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_cover',
            new_name='okladka',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_by',
            new_name='stworzono_przez',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='wydawnictwo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='zdjecie',
        ),
    ]
