# Generated by Django 3.1.7 on 2021-03-10 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_auto_20210310_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_publikacji',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
